[2022-02-17 21:31:16,575] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-02-17T21:31:05.956240+00:00 [queued]>
[2022-02-17 21:31:16,771] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-02-17T21:31:05.956240+00:00 [queued]>
[2022-02-17 21:31:16,774] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 21:31:16,781] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-17 21:31:16,783] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 21:31:16,882] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): also_run_this> on 2022-02-17 21:31:05.956240+00:00
[2022-02-17 21:31:16,914] {standard_task_runner.py:52} INFO - Started process 361 to run task
[2022-02-17 21:31:16,954] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-02-17T21:31:05.956240+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpu92ze19w', '--error-file', '/tmp/tmpv0zvhbid']
[2022-02-17 21:31:16,958] {standard_task_runner.py:77} INFO - Job 13: Subtask also_run_this
[2022-02-17 21:31:17,106] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-02-17T21:31:05.956240+00:00 [running]> on host bd44ee7f0b09
[2022-02-17 21:31:17,474] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-02-17T21:31:05.956240+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-17T21:31:05.956240+00:00
[2022-02-17 21:31:17,478] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-17 21:31:17,488] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-02-17T21:31:05.956240+00:00 | dag_run=<DagRun example_bash_operator @ 2022-02-17 21:31:05.956240+00:00: manual__2022-02-17T21:31:05.956240+00:00, externally triggered: True>"']
[2022-02-17 21:31:17,658] {subprocess.py:85} INFO - Output:
[2022-02-17 21:31:17,836] {subprocess.py:89} INFO - run_id=manual__2022-02-17T21:31:05.956240+00:00 | dag_run=<DagRun example_bash_operator @ 2022-02-17 21:31:05.956240+00:00: manual__2022-02-17T21:31:05.956240+00:00, externally triggered: True>
[2022-02-17 21:31:17,848] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-17 21:31:18,104] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220217T213105, start_date=20220217T213116, end_date=20220217T213118
[2022-02-17 21:31:18,268] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-17 21:31:18,776] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
